// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.GeneratedTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TesteDotNet.Core2_0")]
    public partial class TesteDotNet_Core2_0Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TesteDotNet.Core2_0.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "TesteDotNet.Core2_0", "\tComo um usuário do sistema\r\n\tQuero utilizar as funções do cadastro simples de it" +
                    "ems", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Implementar a funcionalidade de ADICIONAR")]
        [NUnit.Framework.CategoryAttribute("CenarioTeste")]
        public virtual void ImplementarAFuncionalidadeDeADICIONAR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Implementar a funcionalidade de ADICIONAR", new string[] {
                        "CenarioTeste"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("que eu acesse a pagina \"inicial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 10
 testRunner.When("eu clicar no botão \"Novo Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 11
 testRunner.Then("eu verei o texto \"Adicionar Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 12
 testRunner.When("no campo \"Nome\" eu digitar \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 13
 testRunner.And("no campo \"Descricao\" eu digitar \"novaDescricao\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
 testRunner.When("eu selecionar no campo \"CategoriaId\" o valor \"Renda Fixa\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 15
 testRunner.When("eu clicar no botão \"Salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 16
 testRunner.Then("eu verei o item digitado \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Implementar a funcionalidade de ALTERAR")]
        [NUnit.Framework.CategoryAttribute("CenarioTeste")]
        public virtual void ImplementarAFuncionalidadeDeALTERAR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Implementar a funcionalidade de ALTERAR", new string[] {
                        "CenarioTeste"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("que eu acesse a pagina \"inicial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 21
 testRunner.When("eu clicar no botão \"Editar\" do \"Primeiro\" item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 22
 testRunner.Then("eu verei o texto \"Alterar Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 23
 testRunner.When("no campo \"Nome\" eu digitar \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 24
 testRunner.And("no campo \"Descricao\" eu digitar \"novaDescricao\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 25
 testRunner.When("eu selecionar no campo \"CategoriaId\" o valor \"Tesouro Direto\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 26
 testRunner.When("eu clicar no botão \"Salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 27
 testRunner.Then("eu verei o item digitado \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Implementar a funcionalidade de DELETAR")]
        [NUnit.Framework.CategoryAttribute("CenarioTeste")]
        public virtual void ImplementarAFuncionalidadeDeDELETAR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Implementar a funcionalidade de DELETAR", new string[] {
                        "CenarioTeste"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("que eu acesse a pagina \"inicial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 32
 testRunner.When("eu clicar no botão \"Novo Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 33
 testRunner.Then("eu verei o texto \"Adicionar Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 34
 testRunner.When("no campo \"Nome\" eu digitar \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 35
 testRunner.And("no campo \"Descricao\" eu digitar \"novaDescricao\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 36
 testRunner.When("eu selecionar no campo \"CategoriaId\" o valor \"Renda Fixa\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 37
 testRunner.When("eu clicar no botão \"Salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 38
 testRunner.Then("eu verei o item digitado \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 39
 testRunner.When("eu clicar no botão \"Excluir\" do \"Primeiro\" item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 40
 testRunner.And("eu clicar no botão \"Sim\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 41
 testRunner.Then("não verei o texto \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Implementar a funcionalidade de VISUALIZAR")]
        [NUnit.Framework.CategoryAttribute("CenarioTeste")]
        public virtual void ImplementarAFuncionalidadeDeVISUALIZAR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Implementar a funcionalidade de VISUALIZAR", new string[] {
                        "CenarioTeste"});
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("que eu acesse a pagina \"inicial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 46
 testRunner.When("eu clicar no botão \"Novo Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 47
 testRunner.Then("eu verei o texto \"Adicionar Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 48
 testRunner.When("no campo \"Nome\" eu digitar \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 49
 testRunner.And("no campo \"Descricao\" eu digitar \"novaDescricao\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 50
 testRunner.When("eu selecionar no campo \"CategoriaId\" o valor \"Renda Fixa\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 51
 testRunner.When("eu clicar no botão \"Salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 52
 testRunner.Then("eu verei o item digitado \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 53
 testRunner.When("eu clicar no botão \"Visualizar\" do \"Primeiro\" item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 54
 testRunner.Then("eu verei o item digitado \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 55
 testRunner.When("eu clicar no botão \"Voltar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 56
 testRunner.Then("eu verei o texto \"Itens\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Implementar a funcionalidade que 2 items com o mesmo nome são BLOQUEADO")]
        [NUnit.Framework.CategoryAttribute("CenarioTeste")]
        public virtual void ImplementarAFuncionalidadeQue2ItemsComOMesmoNomeSaoBLOQUEADO()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Implementar a funcionalidade que 2 items com o mesmo nome são BLOQUEADO", new string[] {
                        "CenarioTeste"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("que eu acesse a pagina \"inicial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 61
 testRunner.When("eu clicar no botão \"Novo Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 62
 testRunner.Then("eu verei o texto \"Adicionar Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 63
 testRunner.When("no campo \"Nome\" eu digitar \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 64
 testRunner.And("no campo \"Descricao\" eu digitar \"novaDescricao\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 65
 testRunner.When("eu selecionar no campo \"CategoriaId\" o valor \"Renda Fixa\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 66
 testRunner.When("eu clicar no botão \"Salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 67
 testRunner.Then("eu verei o item digitado \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 68
 testRunner.When("eu clicar no botão \"Novo Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 69
 testRunner.When("no campo \"Nome\" eu digitar \"itemAnterior\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 70
 testRunner.And("no campo \"Descricao\" eu digitar \"descricaoAnterior\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 71
 testRunner.When("eu selecionar no campo \"CategoriaId\" o valor \"Tesouro Direto\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 72
 testRunner.When("eu clicar no botão \"Salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 73
 testRunner.Then("eu verei o texto \"Já existe um item cadastrado com o mesmo nome\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Implementar a funcionalidade de busca por Nome")]
        [NUnit.Framework.CategoryAttribute("CenarioTeste")]
        public virtual void ImplementarAFuncionalidadeDeBuscaPorNome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Implementar a funcionalidade de busca por Nome", new string[] {
                        "CenarioTeste"});
#line 76
this.ScenarioSetup(scenarioInfo);
#line 77
 testRunner.Given("que eu acesse a pagina \"inicial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 78
 testRunner.When("eu clicar no botão \"Novo Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 79
 testRunner.Then("eu verei o texto \"Adicionar Item\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 80
 testRunner.When("no campo \"Nome\" eu digitar \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 81
 testRunner.And("no campo \"Descricao\" eu digitar \"novaDescricao\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 82
 testRunner.When("eu selecionar no campo \"CategoriaId\" o valor \"Renda Fixa\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 83
 testRunner.When("eu clicar no botão \"Salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 84
 testRunner.Then("eu verei o item digitado \"novoItem\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 85
 testRunner.When("no campo \"busca\" eu digitar \"textoAleatorio\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 86
 testRunner.And("eu clicar na busca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 87
 testRunner.Then("eu não verei o item digitado \"itemAnterior\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 88
 testRunner.When("no campo \"busca\" eu digitar \"itemAnterior\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 89
 testRunner.And("eu clicar na busca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 90
 testRunner.Then("eu verei o item digitado \"itemAnterior\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
